name: Build GD Deco AI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64
          configure-args: "-DGEODE_DISABLE_FMT_CONSTEVAL=ON"

      - name: Upload Geode mod
        uses: actions/upload-artifact@v4
        with:
          name: GD-Deco-AI-Android64
          path: ${{ steps.build.outputs.build-output }}
